apiVersion: v1
kind: Template
labels:
  app: ${APPLICATION_NAME}
metadata:
  name: ${APPLICATION_NAME}-deployment-route-template
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2019-07-08T03:12:32Z
        status: "True"
        type: Admitted
      routerName: router
      wildcardPolicy: None
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name of the application (i.e. Openshift Application name).
  required: true
