apiVersion: v1
kind: Template
labels:
  app: ${APPLICATION_NAME}
metadata:
  name: ${APPLICATION_NAME}-deployment-service-template
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name of the application (i.e. Openshift Application name).
  required: true
