apiVersion: v1
kind: Template
labels:
  app: ${APPLICATION_NAME}
metadata:
  name: ${APPLICATION_NAME}-kickstart-pipeline-template
  annotations:
    description: A template for creating the kickstart pipeline for the ${APPLICATION_NAME} application.
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}-kickstart
  spec:
    runPolicy: SerialLatestOnly
    source:
      git:
        uri: ${SOURCE_REPO_GIT_URI}
        ref: ${SOURCE_REPO_GIT_BRANCH}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${CICD_RESOURCES_DIRECTORY}/Jenkinsfile-kickstart
        env:
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
      type: JenkinsPipeline
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name of the application (i.e. Openshift Application name).
  required: true
- name: SOURCE_REPO_GIT_URI
  displayName: URI of the source repository
  description: URI of the source repository.
  required: true
- name: SOURCE_REPO_GIT_BRANCH
  displayName: Branch of the source repository
  description: Branch of the source repository.
  required: true
- name: CICD_RESOURCES_DIRECTORY
  displayName: Name of directory where the openshift scripts and yaml files are
  description: Name of directory where the openshift scripts and yaml files are.
  required: true
